# Generated by Django 3.0.3 on 2020-06-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='Address',
        ),
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPV4'),
        ),
    ]
